config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :authors
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :posts, dependent: :destroy

    validates :first_name, presence: true
    validates :last_name, presence: true

    def formatted_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :body, presence: true

  default_scope { order(created_at: :desc) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  default_scope { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    before_action :set_author, only: [:show, :edit, :update, :destroy]

    def index
        @authors = Author.all
    end

    def show
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.create(author_params)        
        respond_to do |format|
            if @author.save
                format.html { redirect_to @author, notice: "#{@author.formatted_name} was successfully saved." }
                # NOTE AUTHOR STEP 1: This will run the code in `app/views/comments/create.js.erb`.
                format.js
            else
                format.html { render 'new' }
                # NOTE AUTHOR STEP 1: This will run the code in `app/views/comments/create.js.erb`.
                format.js
            end
        end
    end

    def edit
    end

    def update
        if @author.update(author_params)
            redirect_to author_path(@author), notice: "#{@author.formatted_name} was successfully updated."
        else
            render 'edit'
        end
    end

    def destroy
        @author.destroy
        redirect_to authors_path, notice: "#{@author.formatted_name} was successfully deleted."
    end

    private 

        def set_author
            @author = Author.find(params[:id])
        end

        def author_params
            params.require(:author).permit(:first_name, :last_name)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:edit, :update, :destroy]
    before_action :set_post, only: [:create, :edit, :update]

    def create
        @comment = @post.comments.create(comment_params)
        respond_to do |format|
            if  @comment.save
                format.html { redirect_to @post, notice: 'Comment was successfully created.' }
                # NOTE COMMENT STEP 1: This will run the code in `app/views/comments/create.js.erb`.
                format.js
            else
                format.html { render action: "new" }
                # NOTE COMMENT STEP 1: This will run the code in `app/views/comments/create.js.erb`.
                format.js
            end
        end
    end

    def edit
    end

    def update
        if @comment.update(comment_params)
            redirect_to @comment.post, notice: "Comment updated."
        else
            render 'edit'
        end
    end

    def destroy
        @comment.destroy
        redirect_to @comment.post, notice: "Comment successfully deleted."
    end

    private

        def set_post
            @post = Post.find(params[:post_id])
        end

        def set_comment
            @comment = Comment.find(params[:id])
        end

        def comment_params
            params.require(:comment).permit(:body)
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :set_post, only: [:show, :edit, :update, :destroy]
    # NOTE AUTHOR STEP 2: This is needed for the new author form to work in `app/views/posts/new.html.erb` and `app/views/posts/edit.html.erb`.
    before_action :new_author, only: [:new, :edit]

    def index
        @posts = Post.all
    end

    def show
        # NOTE COMMENT STEP 2: This is needed in order for `app/views/comments/_form.html.erb` to use `@comment`.
        # NOTE COMMENT STEP 2: Using `@comment = @post.comments.build` did not work. This was becuase `<%= render "comments/form" %>` was being rendered before `<%= render @post.comments %>` in `app/views/posts/show.html.erb`.
        @comment = Comment.new(post: @post)
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.create(post_params)
        if @post.save
            redirect_to @post, notice: "#{@post.title} was successfully saved."
        else
            render "new"
        end
    end

    def edit
    end

    def update
        if @post.update(post_params)
            redirect_to @post, notice: "#{@post.title} was successfully updated."
        else
            render "edit"
        end
    end

    def destroy
        @post.destroy
        redirect_to posts_path, notice: "#{@post.title} was successfully deleted."
    end

    private

        def set_post
            @post = Post.find(params[:id])
        end

        def post_params
            params.require(:post).permit(:title, :body, :author_id)
        end

        def new_author
            @author = Author.new
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper

    def post_excerpt(post)
        sanitize(truncate(post.body, length: 50)) if post && post.body.present?
    end

end

app/views/authors/_author.html.erb
<div class="card mb-3">
    <div class="card-header">
        <h3 class="mb-0"><%= author.formatted_name %></h3>
    </div>
    <div class="card-body">
        <%= link_to "See Posts", author_path(author), class: "btn btn-outline-primary btn-sm" %>
    </div>
</div>

app/views/authors/_form-fields.html.erb
<div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
</div>
<div class="btn-group">
    <%= f.submit class: "btn btn-success" %>
    <%# NOTE AUTHOR Only load the delete button when editing an author. Otherwise the delete button will appear on the new post view and raise an exception. %>
    <% if params[:action] == 'edit' && params[:controller] == 'authors' %>
        <%= link_to "Delete #{@author.formatted_name}", author_path(@author), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <% end %>
</div>

app/views/authors/_form.html.erb
<%# NOTE AUTHOR STEP 2: Conditionally load an AJAX version of the form when on `posts#new`.  %>
<% if params[:controller] === 'posts' %>
    <%# NOTE AUTHOR STEP 2: Assign the form an ID of `author_form` so that you can select the form when using javascript in `app/views/authors/create.js.erb`. %>
    <%# NOTE AUTHOR STEP 2: Don't add `local: true` to this form. Otherwise, AJAX will not work. %>
    <%= form_with model: @author, id: "author_form" do |f| %>
        <%= render 'authors/form-fields', f: f %>
    <% end %>
<%# NOTE AUTHOR STEP 2: Conditionally load a non-AJAX version of the form when on `authors#edit`. %>
<% else %>
    <%= form_with model: @author, local: true  do |f| %>
        <%= render 'shared/validation-messages', object: f.object %>
        <%= render 'authors/form-fields', f: f %>
    <% end %>
<% end %>

app/views/authors/create.js.erb
<%  if @author.errors.any? %>
    <%# NOTE AUTHOR STEP 4: This removes any error messages that were previously generated. %>
    document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
    <%# NOTE AUTHOR STEP 4: This selects the new author `<form>` in `app/views/posts/new.html.erb` and `app/views/posts/edit.html.erb` and dynamically injects the `app/views/shared/_validation-messages.html.erb` partial. %>
    document.querySelector('#author_form').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render "shared/validation-messages", object: @author) %>');
<%  else %>
    <%# NOTE AUTHOR STEP 4: This removes any error messages that were previously generated. %>
    document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
    <%# NOTE AUTHOR STEP 4: This searches for the currently selected author in `app/views/posts/new.html.erb` and `app/views/posts/edit.html.erb`, and unselects them. %>
    document.querySelector("select#post_author_id option[selected='selected']") ? document.querySelector("select#post_author_id option[selected='selected']").removeAttribute('selected') : null ;
    <%# NOTE AUTHOR STEP 4: This dynamically adds the newly created author into the author select list, and sets them to be selected. %>
    document.querySelector('select#post_author_id').insertAdjacentHTML('afterbegin', '<option value="<%= @author.id %>" selected="selected" ><%= @author.formatted_name %></option>') ;
    <%# NOTE AUTHOR STEP 4: This selects the new author `<form>` in `app/views/posts/new.html.erb` and `app/views/posts/edit.html.erb` and resets the fields. %>
    document.querySelector('#author_form').reset();
<%  end %>

app/views/authors/edit.html.erb
<div class="card mb-3">
    <div class="card-header">
        <h1 class="mb-0">Edit <%= @author.formatted_name %></h1>
    </div>
    <div class="card-body">
        <%= render 'form' %>
    </div>    
</div>

app/views/authors/index.html.erb
<div class="card mb-5">
    <div class="card-header">
        <h1 class="mb-0">Authors</h1>
    </div>
    <div class="card-body">
        <%= link_to "Add New Author", new_author_path, class: "btn btn-primary btn-large" %>
    </div>
</div>
<%= render @authors %>

app/views/authors/new.html.erb
<div class="card mb-3">
    <div class="card-header">
        <h1 class="mb-0">Add a New Author</h1>
    </div>
    <div class="card-body">
        <%= render 'form' %>
    </div>
</div>

app/views/authors/show.html.erb
<div class="card mb-3">
    <div class="card-header">
        <h1 class="mb-0">Posts by <%= @author.formatted_name %></h1>
    </div>
    <div class="card-body">
        <%= link_to "Edit Author", edit_author_path(@author), class: "btn btn-primary" %>
    </div>
</div>
<div id="posts" class="pb-5">
    <%= render @author.posts %>
</div>

app/views/comments/_comment.html.erb
<div class="py-3 border-bottom comment comment-<%= comment.id%>">
    <small class="d-inline-block mb-3 text-secondary border-bottom">Posted <%= time_ago_in_words(comment.created_at) %> ago.</small>
    <p><%= comment.body %></p>
    <div class="btn-group">
        <%= link_to "Edit Comment", edit_post_comment_path(comment.post, comment), class: "btn btn-sm btn-outline-primary" %>
        <%= link_to "Delete Comment", post_comment_path(comment.post, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-danger" %>
    </div>
</div>

app/views/comments/_form-fields.html.erb
<div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
</div>
<div class="btn-group">    
    <%= f.submit class: "btn btn-success" %>
</div>

app/views/comments/_form.html.erb
<%# NOTE COMMENT STEP 2: Conditionally load an AJAX version of the form when on `posts#show`. %>
<% if params[:controller] === 'posts' %>
    <%# NOTE COMMENT STEP 2: Assign the form an ID of `comments-form` so that you can select the form when using javascript in `app/views/comments/create.js.erb`. %>
    <%# NOTE COMMENT STEP 2: Don't add `local: true` to this form. Otherwise, AJAX will not work. %>
    <%= form_with model:[@post, @comment], id: "comments-form" do |f| %>
        <%= render 'comments/form-fields', f: f %>
    <% end  %>
<%# NOTE COMMENT STEP 2: Conditionally load a non-AJAX version of the form when on `comments#edit`. %>
<% else  %>
    <%= form_with model:[@post, @comment], local: true do |f| %>
        <%= render "shared/validation-messages", object: f.object %>
        <%= render 'comments/form-fields', f: f %>
    <% end  %>
<% end  %>

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
    <%# NOTE COMMENT STEP 4: This removes any error messages that were previously generated. %>
    document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
    <%# NOTE COMMENT STEP 4: This selects the `<form>` in `app/views/posts/show.html.erb` and dynamically injects the `app/views/shared/_validation-messages.html.erb` partial. %>
    document.querySelector('#comments-form').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render "shared/validation-messages", object: @comment) %>');
<% else %>
    <%# NOTE COMMENT STEP 4: This removes any error messages that were previously generated. %>
    document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
    <%# NOTE COMMENT STEP 4: This selects `<div id="comments">` in `app/views/posts/show.html.erb` and dynamically injects the `app/views/comments/_comment.html.erb` partial. %>
    document.querySelector('#comments').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render @comment) %>') ;
    <%# NOTE COMMENT STEP 4: This selects the `<form>` in `app/views/posts/show.html.erb` and resets the text area. %>
    document.querySelector('#comments-form').reset();
<% end %>

app/views/comments/edit.html.erb
<div class="card">
    <div class="card-header">
        <h1 class="mb-0">Edit Comment</h1>
    </div>
    <div class="card-body">
        <%= render "form" %>
    </div>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Ajax Examples | Steve Polito Design</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="pb-5">
      <%= render 'shared/header' %>
      <%= render 'shared/flash' %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render 'shared/debug' %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
    <%= render "shared/validation-messages", object: f.object %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :author_id, "Author" %>
        <%= f.collection_select(:author_id, Author.all, :id, :formatted_name, {}, { class: "form-control" }) %>
    </div>
    <div class="btn-group">
        <%= f.submit class: "btn btn-success" %>
        <%# NOTE Only show the delete button on the edit page. Otherwise it would appear when adding a new post. %>
        <% if params[:action] == 'edit' %>
            <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"  %>
        <% end %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<article class="card mb-3 post post-<%= post.id %>">
    <div class="card-header">
        <h3 class="mb-0"><%= post.title %></h3>
    </div>
    <div class="card-body">
        <small class="d-inline-block mb-3 text-secondary border-bottom">Posted by: <%= link_to post.author.formatted_name, author_path(post.author) %> <%= time_ago_in_words(post.created_at) %> ago.</small>
        <p class="card-text"><%= post_excerpt(post) %></p>
        <%= link_to "Read More", post_path(post), class: "btn btn-sm btn-outline-primary" %>
    </div>
</article>

app/views/posts/edit.html.erb
<div class="row mb-3">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h1 class="mb-0">Edit <%= @post.title %></h1>
            </div>
            <div class="card-body">
                <%= render "form" %>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Quickly add an Author using the form below.</h3>
                <%= render "authors/form" %>
            </div>
        </div>
    </div>    
</div>

app/views/posts/index.html.erb
<div class="card mb-5">
    <div class="card-header">
        <h1 class="mb-0">Posts</h1>
    </div>
    <div class="card-body">
        <%= link_to "Add New Post", new_post_path, class: "btn btn-primary btn-large" %>
    </div>
</div>
<section id="posts">
    <%= render @posts %>
</section>

app/views/posts/new.html.erb
<div class="row">
    <div class="col-md-8 mb-3">
        <div class="card">
            <div class="card-header">
                <h1 class="mb-0">New Post</h1>
            </div>
            <div class="card-body">
                <%= render "form" %>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h3 class="mb-0">Quickly add an Author using the form below.</h3>
            </div>        
            <div class="card-body">
                <%# NOTE AUTHOR STEP 3: Load the author form %>
                <%= render "authors/form" %>
            </div>
        </div>
    </div>    
<div>

app/views/posts/show.html.erb
<div class="card mb-3">
    <div class="card-header">
        <h1 class="mb-0"><%= @post.title %></h1>
    </div>
    <div class="card-body">
        <small class="d-inline-block mb-3 text-secondary border-bottom">Posted by: <%= link_to @post.author.formatted_name, author_path(@post.author) %> <%= time_ago_in_words(@post.created_at) %> ago.</small>
        <p><%= @post.body %></p>
        <%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-primary" %>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header">
        <h4 class="mb-0">Add A Comment:</h4>
    </div>
    <div class="card-body">
        <%# NOTE COMMENT STEP 3: Load the comment form. %>
        <%= render "comments/form" %>
    </div>
</div>
<div class="card mb-3">
    <div class="card-header">
        <h4>Comments:</h4>
    </div>
    <%# NOTE COMMENT STEP 3: Wrap the comments in `<div id="comments">` so that you can select the wrapper when using javascript in `app/views/comments/create.js.erb`. %>
    <div id="comments" class="card-body">
        <%= render @post.comments %>
    </div>
</div>

app/views/shared/_debug.html.erb
<% if Rails.env.development? %>
    <div class="container">
        <div class="card">
            <div class="card-header">
                Params
            </div>
            <div class="card-body">
                    <code>
                        <%= debug(params) %>
                    </code>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="container">
    <div class="alert <%= type == "notice" ? 'alert-success' : 'alert-danger' %>" role="alert">
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5 sticky-top shadow-sm">
    <div class="container">
        <%= link_to "Home", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Posts", posts_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Authors", authors_path, class: "nav-link" %>
                </li>         
            </ul>
        </div>
    </div>
</nav>

app/views/shared/_validation-messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
        <p class="font-weight-bold"><%= pluralize(object.errors.count, "error") %> prohibited this <%= "#{object.class.name.downcase}" %> from being saved:</p>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>